# Generated by Django 4.1.3 on 2022-12-10 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aum',
            name='period',
            field=models.DateField(),
        ),
    ]
