# Generated by Django 4.1.3 on 2022-12-10 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_aum_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aum',
            name='value',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
