# Generated by Django 4.1.3 on 2022-12-15 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_acc_ballance'),
    ]

    operations = [
        migrations.AddField(
            model_name='acc_ballance',
            name='scheme',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
