# Generated by Django 4.1.3 on 2022-12-15 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_acc_ballance_scheme'),
    ]

    operations = [
        migrations.AddField(
            model_name='acc_ballance',
            name='last_cont_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
