# Generated by Django 4.1.3 on 2022-12-15 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_acc_ballance_last_cont_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='acc_ballance',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
