# Generated by Django 4.1.3 on 2022-12-16 14:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0008_alter_acc_ballance_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='all_scheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheme', models.CharField(blank=True, max_length=10, null=True)),
                ('contribution', models.FloatField(default=0.0)),
                ('last_cont_date', models.DateField(blank=True, null=True)),
                ('interest', models.FloatField(default=0.0)),
                ('withdrawal', models.FloatField(default=0.0)),
                ('balance', models.FloatField(default=0.0)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
