# Generated by Django 4.1.3 on 2022-12-16 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_all_scheme'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='all_scheme',
            name='scheme',
        ),
    ]
