# Generated by Django 4.1.3 on 2022-12-05 20:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dob', models.DateField()),
                ('gender', models.CharField(blank=True, max_length=25, null=True)),
                ('country', models.CharField(blank=True, max_length=250, null=True)),
                ('country_of_birth', models.CharField(blank=True, max_length=250, null=True)),
                ('place_of_birth', models.CharField(blank=True, max_length=250, null=True)),
                ('phone', models.CharField(blank=True, max_length=25, null=True)),
                ('alt_phone', models.CharField(blank=True, max_length=25, null=True)),
                ('dig_address', models.CharField(blank=True, max_length=250, null=True)),
                ('postal_address', models.CharField(blank=True, max_length=250, null=True)),
                ('ssnit', models.CharField(blank=True, max_length=25, null=True)),
                ('national_id', models.CharField(blank=True, max_length=50, null=True)),
                ('nok', models.CharField(blank=True, max_length=200, null=True)),
                ('nok_address', models.CharField(blank=True, max_length=25, null=True)),
                ('nok_rel', models.CharField(blank=True, max_length=25, null=True)),
                ('nok_phone', models.CharField(blank=True, max_length=25, null=True)),
                ('father_name', models.CharField(blank=True, max_length=100, null=True)),
                ('father_address', models.CharField(blank=True, max_length=250, null=True)),
                ('mother_name', models.CharField(blank=True, max_length=100, null=True)),
                ('mother_address', models.CharField(blank=True, max_length=250, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
