# Generated by Django 4.1.3 on 2022-12-05 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profil_pic',
            field=models.ImageField(default='ava.jpeg', upload_to='profile-pics'),
        ),
    ]
