# Generated by Django 4.1.3 on 2022-12-05 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_profile_profil_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='cover_pic',
            field=models.ImageField(default='cover.jpeg', upload_to='cover-pics'),
        ),
    ]
