# Generated by Django 4.1.3 on 2022-12-05 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_profile_other_names'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='account',
            field=models.CharField(blank=True, max_length=250, null=True, unique=True),
        ),
    ]
