# Generated by Django 4.1.3 on 2022-12-07 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_alter_profile_cover_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='cover_pic',
            field=models.ImageField(default='cover.jpeg', upload_to='cover-pics'),
        ),
    ]
