# Generated by Django 4.1.3 on 2022-12-13 19:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0015_clientaum'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientaum',
            name='scheme',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='clientaum',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='ClientPortfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheme', models.CharField(blank=True, max_length=10, null=True)),
                ('total_cont', models.FloatField(blank=True, null=True)),
                ('total_int', models.FloatField(blank=True, null=True)),
                ('total_with', models.FloatField(blank=True, null=True)),
                ('curr_balance', models.FloatField(blank=True, null=True)),
                ('total_months', models.FloatField(blank=True, null=True)),
                ('last_paid_date', models.DateField()),
                ('updated', models.DateField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
