# Generated by Django 4.1.3 on 2022-12-14 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_clientaum_scheme_clientaum_updated_clientportfolio'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='target',
            field=models.PositiveIntegerField(blank=True, default=15, null=True),
        ),
    ]
