# Generated by Django 4.1.3 on 2022-12-14 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_profile_target'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='target',
            field=models.FloatField(blank=True, default=25.0, null=True),
        ),
    ]
