# Generated by Django 4.1.3 on 2022-12-20 22:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0019_beneficiary'),
    ]

    operations = [
        migrations.RenameField(
            model_name='beneficiary',
            old_name='first_name',
            new_name='b_first_name',
        ),
        migrations.RenameField(
            model_name='beneficiary',
            old_name='last_name',
            new_name='b_last_name',
        ),
        migrations.RemoveField(
            model_name='beneficiary',
            name='user',
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='b_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
