# Generated by Django 4.1.3 on 2022-12-21 17:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0021_rename_b_first_name_beneficiary_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficiary',
            name='first_name',
            field=models.CharField(default='Name', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='beneficiary',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
