# Generated by Django 4.1.3 on 2022-12-21 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0022_alter_beneficiary_first_name_alter_beneficiary_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficiary',
            name='first_name',
            field=models.CharField(blank=True, default='Name', max_length=250, null=True),
        ),
    ]
