# Generated by Django 4.1.3 on 2022-12-21 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0023_alter_beneficiary_first_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficiary',
            name='first_name',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
    ]
